// B6-P1 test vectors, generated by @bsv/sdk (version pinned in package.json) — never by Hodos code.
// Writes rust-wallet/tests/fixtures/authfetch_vectors.json.
//   nonces:    createNonce's exact body (createNonce.js) with the 16 random bytes fixed, per prefix
//   sdkNonces: real createNonce output (SDK's own Random) — Rust verify must accept them
//   replies:   a real SDK Peer acting as server, answering an initialRequest carrying a
//              Hodos-format nonce; the captured initialResponse is what Rust must accept
import { writeFileSync, readFileSync } from 'node:fs'
import { PrivateKey, ProtoWallet, Peer, Utils, createNonce } from '@bsv/sdk'

const sdkVersion = JSON.parse(readFileSync(new URL('./node_modules/@bsv/sdk/package.json', import.meta.url))).version
const CLIENT_PRIV = 'e8f32e723decf4051aefac8e2c93c9c5b214313817cdb01a1494b917c8436b35'
const SERVER_PRIV = 'c9afa9d845ba75166b5c215767b1d6934e50c3db36e89b127b8a622b120f6721'
const client = new ProtoWallet(new PrivateKey(CLIENT_PRIV, 'hex'))
const server = new ProtoWallet(new PrivateKey(SERVER_PRIV, 'hex'))
const clientPub = (await client.getPublicKey({ identityKey: true })).publicKey
const serverPub = (await server.getPublicKey({ identityKey: true })).publicKey

const prefixes = {
  ascii: Utils.toArray('0123456789abcdef', 'utf8'),
  invalid_utf8: [0xff, 0xfe, 0x80, 0xc3, 0x28, 0xa0, 0xa1, 0xe2, 0x28, 0xa1, 0xf0, 0x28, 0x8c, 0xbc, 0xed, 0xa0],
  leading_bom: [0xef, 0xbb, 0xbf, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d],
  embedded_nul: [0x41, 0x00, 0x42, 0x00, 0x43, 0x00, 0x44, 0x00, 0x45, 0x00, 0x46, 0x00, 0x47, 0x00, 0x48, 0x00],
  valid_multibyte: [0xe2, 0x82, 0xac, 0xc3, 0xa9, 0xf0, 0x9f, 0x98, 0x80, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47],
  truncated_tail: [0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0xf0, 0x9f, 0x98],
  bom_not_at_start: [0x41, 0xef, 0xbb, 0xbf, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d],
  lone_continuation: [0x80, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e, 0x4f],
  overlong: [0xc0, 0xaf, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e],
  surrogate: [0xed, 0xa0, 0x80, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d],
  truncated_mid: [0xe2, 0x82, 0x41, 0x42, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4a, 0x4b, 0x4c, 0x4d, 0x4e]
}
// A prefix whose derived HMAC key has a leading 0x00: the SDK keys HMAC with the 31-byte
// minimal form (BigNumber.toArray()), not 32 bytes. Searched deterministically.
{
  const { KeyDeriver } = await import('@bsv/sdk')
  const kd = new KeyDeriver(new PrivateKey(CLIENT_PRIV, 'hex'))
  for (let i = 0; ; i++) {
    const p = Utils.toArray(('lz' + i).padEnd(16, '_'), 'utf8')
    if (kd.deriveSymmetricKey([2, 'server hmac'], Utils.toUTF8(p), 'self').toArray().length < 32) { prefixes.leading_zero_key = p; break }
  }
}

const nonces = []
for (const [name, firstHalf] of Object.entries(prefixes)) {
  // createNonce.js body, verbatim except Random(16) → firstHalf
  const { hmac } = await client.createHmac({ protocolID: [2, 'server hmac'], keyID: Utils.toUTF8(firstHalf), data: firstHalf, counterparty: 'self' })
  const nonce = Utils.toBase64([...firstHalf, ...hmac])
  if (!(await (await import('@bsv/sdk')).verifyNonce(nonce, client))) throw new Error('SDK rejects its own vector ' + name)
  nonces.push({ name, firstHalfHex: Utils.toHex(firstHalf), keyIdUtf8Hex: Utils.toHex(Utils.toArray(Utils.toUTF8(firstHalf), 'utf8')), nonce })
}

const sdkNonces = []
for (let i = 0; i < 8; i++) sdkNonces.push(await createNonce(client))

// Real Peer as server: feed it an initialRequest via a fake transport, capture the initialResponse.
async function serverReply (clientNonce) {
  let onData; let sent
  const transport = { send: async m => { sent = m }, onData: async cb => { onData = cb } }
  const peer = new Peer(server, transport)
  await new Promise(r => setTimeout(r, 0))
  await onData({ version: '0.1', messageType: 'initialRequest', identityKey: clientPub, initialNonce: clientNonce })
  return sent
}
const replies = []
for (const n of [nonces[0].nonce, nonces[1].nonce, sdkNonces[0]]) {
  const reply = await serverReply(n)
  replies.push({ clientNonce: n, reply })
}

const out = {
  generator: 'development-docs/0.4.0-beta.6/g2-validator/gen_authfetch_vectors.mjs',
  sdkVersion,
  clientPrivHex: CLIENT_PRIV,
  clientPubHex: clientPub,
  serverPubHex: serverPub,
  nonces,
  sdkNonces,
  replies
}
const dest = new URL('../../../rust-wallet/tests/fixtures/authfetch_vectors.json', import.meta.url)
writeFileSync(dest, JSON.stringify(out, null, 1) + '\n')
console.log('sdk', sdkVersion, 'nonces', nonces.length, 'sdkNonces', sdkNonces.length, 'replies', replies.length)
console.log(JSON.stringify(replies[0].reply).slice(0, 400))
